service: smart-brain-api
provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-west-2
functions:
  rank:
    handler: handler.rank
    events:
      - http:
          path: /
          method: get
